export const SEARCHING_ITEMS = "SEARCHING_ITEMS";
export const SEARCHING_ITEMS_SUCCESS = "SEARCHING_ITEMS_SUCCESS";
export const SEARCHING_ITEMS_FAILED = "SEARCHING_ITEMS_FAILED";

export const SEARCHING_ITEM_DETAIL = "SEARCHING_ITEM_DETAIL";
export const SEARCHING_ITEM_DETAIL_SUCCESS = "SEARCHING_ITEM_DETAIL_SUCCESS";
export const SEARCHING_ITEM_DETAIL_FAILED = "SEARCHING_ITEM_DETAIL_FAILED";
